[application]

[application.tcp]

[application.tcp.socket_address]
value = "0.0.0.0:80"

[application.tcp.nodelay]
value = false

[application.tcp.sleep_on_accept_errors]
value = false

[application.tcp.keepalive_seconds]
value = 60
is_active = false

[application.http]

[application.http.adaptive_window]
value = false

[application.http.connection_window_size]
value = 1048576    #1MB

[application.http.stream_window_size]
value = 1048576    #1MB

[application.http.maximum_frame_size]
value = 16384  #16KB

[application.http.maximum_sending_buffer_size]
value = 409600    #400KB

[application.http.http2_only]
value = true

[application.http.keep_alive]
is_active = false

[application.http.keep_alive.interval_seconds]
value = 5

[application.http.keep_alive.timeout_seconds]
value = 20

[resource]

[resource.postgresql]

[resource.postgresql.database_1_url]
value = "postgres://root:password@database_1_postgresql/tento"

[resource.postgresql.database_2_url]
value = "postgres://root:password@database_2_postgresql/tento"

[resource.redis]

[resource.redis.database_1_url]
value = "redis://redis"

[resource.email_server]

[resource.email_server.socket_address]
value = "mailhog:1025"

[encryption]

[encryption.private_key]

[encryption.private_key.application_user_access_token]
value = "JJJDffsFi3sc8Mz2udB0qRbz8zH12asu4S1ksSsZ6e2v8cs5fFm6dcfLksWeYY2i"

[encryption.private_key.application_user_access_refresh_token]
value = "SSSDffsFi3sc8Mz2idB0qRbz8zH12asu4S1wsSsZ6e2v8cs5fFm6dcfLksWeYY0i"