pub struct DateTimeExpirationStorage;

impl DateTimeExpirationStorage {
    pub const QUANTITY_OF_MINUTES_APPLICATION_USER_LOG_IN_TOKEN_FIRST: u8 = 10;
    pub const QUANTITY_OF_MINUTES_APPLICATION_USER_REGISTRATION_CONFIRMATION_TOKEN_FIRST: u8 = 60 * 24;
    pub const QUANTITY_OF_MINUTES_APPLICATION_USER_RESET_PASSWORD_TOKEN_FIRST: u8 = 10;
    pub const QUANTITY_OF_MINUTES_JSON_ACCESS_WEB_TOKEN_FIRST: u8 = 30;
    pub const QUANTITY_OF_MINUTES_JSON_REFRESH_WEB_TOKEN_FIRST: u8 = 60 * 24 * 21;
}