[[bin]]
name = "core"
path = "./mod.rs"
test = true
doctest = true
bench = true
doc = true
proc-macro = false
harness = true
edition = "2021"
required-features = []

[package]
name = "core"
version = "1.0.0"
authors.workspace = true
rust-version.workspace = true
edition = "2021"

[lints]
workspace = true

[dependencies]
application = { path = "./../../../../..", package = "application", version = "=1.0.0", default-features = true, features = [], optional = false }
clap = { package = "clap", version = "=4.5.17", default-features = true, features = ["cargo"], optional = false }
formatter = { path = "./../../../../../forced_crate/formatter", package = "formatter", version = "=1.0.0", default-features = true, features = [], optional = false }
aggregate_error = { path = "./../../../../../forced_crate/aggregate_error", package = "aggregate_error", version = "=1.0.0", default-features = true, features = [], optional = false }