[system]

[system.tokio]

[system.tokio.worker_threads_quantity]
value = 2

# It is better that the number be greater or equal to 2MiB
[system.tokio.worker_thread_stack_size]
value = 2097152

[logging]

[logging.directory_path]
value = "/_log"

[logging.file_name_prefix]
value = "log"

[resource]

[resource.postgresql]

[resource.postgresql.database_1]

[resource.postgresql.database_1.url]
value = "postgres://root:password@postgresql_database_1/tento"

[resource.postgresql.database_1.maximum_connection_pool_size]
value = 1

# In milliseconds.
[resource.postgresql.database_1.connection_pool_waiting_timeout_duration]
value = 300

[resource.postgresql.database_2]

[resource.postgresql.database_2.url]
value = "postgres://root:password@postgresql_database_2/tento"

[resource.postgresql.database_2.maximum_connection_pool_size]
value = 1

# In milliseconds.
[resource.postgresql.database_2.connection_pool_waiting_timeout_duration]
value = 300

[resource.postgresql.database_3]

[resource.postgresql.database_3.url]
value = "postgres://root:password@postgresql_database_3/tento"

[resource.postgresql.database_3.maximum_connection_pool_size]
value = 1

# In milliseconds.
[resource.postgresql.database_3.connection_pool_waiting_timeout_duration]
value = 300