[rust_crate]

[rust_crate.tokio]

# The number SHOULD be less than the 'rust_crate.rayon.threads_quantity.value' and
# in summ with 'rust_crate.rayon.threads_quantity.value' it SHOULD be less or equal
# to the number of threads that the hardware can handle simultaneously.
[rust_crate.tokio.worker_threads_quantity]
value = 2

# It is better that the number be greater or equal to 2MiB
[rust_crate.tokio.worker_thread_stack_size]
value = 2097152

[rust_crate.rayon]

# The number SHOULD be greater than the 'rust_crate.tokio.worker_threads_quantity].value' and
# in summ with 'rust_crate.tokio.worker_threads_quantity].value' it SHOULD be less or equal
# to the number of threads that the hardware can handle simultaneously.
[rust_crate.rayon.threads_quantity]
value = 3

[application_server]

[application_server.tcp]

[application_server.tcp.socket_address]
value = "0.0.0.0:80"

[application_server.tcp.nodelay]
value = false

[application_server.tcp.sleep_on_accept_errors]
value = false

[application_server.tcp.keepalive]

[application_server.tcp.keepalive.duration]
value = 3
is_exist = false

[application_server.tcp.keepalive.interval_duration]
value = 1
is_exist = false

[application_server.tcp.keepalive.retries_quantity]
value = 3
is_exist = false

[application_server.http]

[application_server.http.adaptive_window]
value = false

#1MiB
[application_server.http.connection_window_size]
value = 1048576

#1MiB
[application_server.http.stream_window_size]
value = 1048576

#16KiB
[application_server.http.maximum_frame_size]
value = 16384

#400KiB
[application_server.http.maximum_sending_buffer_size]
value = 409600

[application_server.http.enable_connect_protocol]
value = false

#1MiB
[application_server.http.maximum_header_list_size]
value = 1048576

[application_server.http.maximum_pending_accept_reset_streams]
value = 20
is_exist = false

[application_server.http.keepalive]
is_exist = false

[application_server.http.keepalive.interval_duration]
value = 5

[application_server.http.keepalive.timeout_duration]
value = 20

[application_server.http.tls]
is_exist = false

[application_server.http.tls.certificate_crt_file_path]
value = ""

[application_server.http.tls.certificate_key_file_path]
value = ""

[logging]

[logging.directory_path]
value = "/_log"

[logging.file_name_prefix]
value = "log"

[resource]

[resource.postgresql]

[resource.postgresql.database_1]

[resource.postgresql.database_1.url]
value = "postgres://root:password@postgresql_database_1/tento"

[resource.postgresql.database_1.maximum_connection_pool_size]
value = 1

# In milliseconds.
[resource.postgresql.database_1.connection_pool_waiting_timeout_duration]
value = 300

[resource.postgresql.database_2]

[resource.postgresql.database_2.url]
value = "postgres://root:password@postgresql_database_2/tento"

[resource.postgresql.database_2.maximum_connection_pool_size]
value = 1

# In milliseconds.
[resource.postgresql.database_2.connection_pool_waiting_timeout_duration]
value = 300

[resource.postgresql.database_3]

[resource.postgresql.database_3.url]
value = "postgres://root:password@postgresql_database_3/tento"

[resource.postgresql.database_3.maximum_connection_pool_size]
value = 1

# In milliseconds.
[resource.postgresql.database_3.connection_pool_waiting_timeout_duration]
value = 300

[resource.postgresql.database_4]

[resource.postgresql.database_4.url]
value = "postgres://root:password@postgresql_database_4/tento"

[resource.postgresql.database_4.maximum_connection_pool_size]
value = 1

# In milliseconds.
[resource.postgresql.database_4.connection_pool_waiting_timeout_duration]
value = 300

[resource.email_server]

[resource.email_server.socket_address]
value = "mailhog:1025"

[encryption]

[encryption.private_key]

[encryption.private_key.user_access_token]
value = "JJJDffsFi3sc8Mz2udB0qRbz8zH12asu4S1ksSsZ6e2v8cs5fFm6dcfLksWeYY2i"

[encryption.private_key.user_access_refresh_token]
value = "SSSDffsFi3sc8Mz2idB0qRbz8zH12asu4S1wsSsZ6e2v8cs5fFm6dcfLksWeYY0i"

[encryption.private_key.channel_token]
value = "Sx8shsdc212asu4S1wsjdncuic0wjbhhjdfviijvisjdjvurnad[ckiW2jwdmkmi"

[encryption.private_key.channel_subscription_token]
value = "Sx81i8dc212asu4S1wsjdncuic0wjbhhjmdiiijvisjdjvurnad[88iW2jwdmbso"

[encryption.private_key.channel_publication1_token]
value = "SSUshsdc212asu4S1wsSsZ6e2v8cf0wjbhhjdfviijvisjdjvurnad[ckiWeYY0i"

[encryption.private_key.channel_publication1_commentary_token]
value = "SSUs18mq212asu4S1wsSsZ6e2v8cf0woxihjdfviijvisjdjvurnad[cki0akdd0i"