[tokio_runtime]

# It is better that the number be greater or equal to 512. It all depends on the workload
# of blocking tasks - these are tasks that take more than 1ms of CPU time.
[tokio_runtime.maximum_blocking_threads_quantity]
value = 128

# It is better that the number be equal to the number of threads that the hardware
# can handle simultaneously.
[tokio_runtime.worker_threads_quantity]
value = 3

# It is better that the number be greater or equal to 2MiB
[tokio_runtime.worker_thread_stack_size]
value = 2097152

[application_server]

[application_server.tcp]

[application_server.tcp.socket_address]
value = "0.0.0.0:80"

[application_server.tcp.nodelay]
value = false

[application_server.tcp.sleep_on_accept_errors]
value = false

[application_server.tcp.keepalive]

[application_server.tcp.keepalive.duration]
value = 3
is_exist = false

[application_server.tcp.keepalive.interval_duration]
value = 1
is_exist = false

[application_server.tcp.keepalive.retries_quantity]
value = 3
is_exist = false

[application_server.http]

[application_server.http.adaptive_window]
value = false

[application_server.http.connection_window_size]
value = 1048576    #1MiB

[application_server.http.stream_window_size]
value = 1048576    #1MiB

[application_server.http.maximum_frame_size]
value = 16384  #16KiB

[application_server.http.maximum_sending_buffer_size]
value = 409600    #400KiB

[application_server.http.enable_connect_protocol]
value = false

[application_server.http.maximum_header_list_size]
value = 1048576    #1MiB

[application_server.http.maximum_pending_accept_reset_streams]
value = 20
is_exist = false

[application_server.http.keepalive]
is_exist = false

[application_server.http.keepalive.interval_duration]
value = 5

[application_server.http.keepalive.timeout_duration]
value = 20

[application_server.http.tls]
is_exist = false

[application_server.http.tls.certificate_crt_file_path]
value = ""

[application_server.http.tls.certificate_key_file_path]
value = ""

[logging]

[logging.directory_path]
value = "/_log"

[logging.file_name_prefix]
value = "log"

[resource]

[resource.postgresql]

[resource.postgresql.database_1]

[resource.postgresql.database_1.url]
value = "postgres://root:password@postgresql_database_1/tento"

[resource.postgresql.database_1.maximum_connection_pool_size]
value = 1

# In milliseconds.
[resource.postgresql.database_1.connection_pool_waiting_timeout_duration]
value = 300

[resource.postgresql.database_2]

[resource.postgresql.database_2.url]
value = "postgres://root:password@postgresql_database_2/tento"

[resource.postgresql.database_2.maximum_connection_pool_size]
value = 1

# In milliseconds.
[resource.postgresql.database_2.connection_pool_waiting_timeout_duration]
value = 300

[resource.postgresql.database_3]

[resource.postgresql.database_3.url]
value = "postgres://root:password@postgresql_database_3/tento"

[resource.postgresql.database_3.maximum_connection_pool_size]
value = 1

# In milliseconds.
[resource.postgresql.database_3.connection_pool_waiting_timeout_duration]
value = 300

[resource.email_server]

[resource.email_server.socket_address]
value = "mailhog:1025"

[encryption]

[encryption.private_key]

[encryption.private_key.user_access_token]
value = "JJJDffsFi3sc8Mz2udB0qRbz8zH12asu4S1ksSsZ6e2v8cs5fFm6dcfLksWeYY2i"

[encryption.private_key.user_access_refresh_token]
value = "SSSDffsFi3sc8Mz2idB0qRbz8zH12asu4S1wsSsZ6e2v8cs5fFm6dcfLksWeYY0i"