version: '3.8'

services:
    core_postgresql:
        container_name: tento_core_postgresql
        build:
            context: ./service/postgresql
            dockerfile: dockerfile
        environment:
            PGDATA: '/var/lib/postgresql/data'
            POSTGRES_HOST_AUTH_METHOD: 'md5'
            POSTGRES_USER: 'root'
            POSTGRES_PASSWORD: 'password'
            POSTGRES_DB: 'tento'
        volumes:
            - core_postgresql_data:/var/lib/postgresql/data
        restart: always
    postgresql_authorization:
        container_name: tento_postgresql_authorization
        build:
            context: ./service/postgresql
            dockerfile: dockerfile
        environment:
            PGDATA: '/var/lib/postgresql/data'
            POSTGRES_HOST_AUTH_METHOD: 'md5'
            POSTGRES_USER: 'root'
            POSTGRES_PASSWORD: 'password'
            POSTGRES_DB: 'tento'
        volumes:
            - postgresql_authorization_data:/var/lib/postgresql/data
        restart: always
    redis:
        container_name: tento_redis
        build:
            context: ./service/redis
            dockerfile: dockerfile
        restart: always
    redis_client:
        container_name: tento_redis_client
        build:
            context: ./service/redis_client
            dockerfile: dockerfile
        ports:
        - 5001:5001
        restart: always
    mailhog:
        container_name: tento_mailhog
        build:
            context: ./service/mailhog
            dockerfile: dockerfile
        ports:
        - 8025:8025
        restart: always

volumes:
    core_postgresql_data:
        driver: local
    postgresql_authorization_data:
        driver: local

networks:
    default:
        external: true
        name: resource