version: '3.8'

services:
    postgresql:
        container_name: memis_postgresql
        build:
            context: ./service/postgresql
            dockerfile: dockerfile
        environment:
            PGDATA: '/var/lib/postgresql/data'
            POSTGRES_HOST_AUTH_METHOD: 'md5'
            POSTGRES_USER: 'root'
            POSTGRES_PASSWORD: 'password'
            POSTGRES_DB: 'memis'
        volumes:
            - postgresql_data:/var/lib/postgresql/data
        restart: always
    redis:
        container_name: memis_redis
        build:
            context: ./service/redis
            dockerfile: dockerfile
        restart: always
    mailhog:
        container_name: memis_mailhog
        build:
            context: ./service/mailhog
            dockerfile: dockerfile
        ports:
        - 8025:8025
        restart: always

volumes:
    postgresql_data:
        driver: local