#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct CVector_c_uchar {
  unsigned char *pointer;
  size_t length;
} CVector_c_uchar;

typedef struct CResult_CVector_c_uchar {
  struct CVector_c_uchar data;
  bool is_data;
} CResult_CVector_c_uchar;

typedef struct CString {
  char *pointer;
} CString;

typedef struct UserAuthorization_AuthorizeByFirstStep_Incoming {
  struct CString user_device__id;
  struct CString user__email___or___user__nickname;
  struct CString user__password;
} UserAuthorization_AuthorizeByFirstStep_Incoming;

typedef struct UserAuthorization_AuthorizeByFirstStep_Outcoming {
  long user__id;
  bool verification_message_sent;
  long user_authorization_token__can_be_resent_from;
  short user_authorization_token__wrong_enter_tries_quantity;
  short user_authorization_token__wrong_enter_tries_quantity_limit;
} UserAuthorization_AuthorizeByFirstStep_Outcoming;

typedef struct CData_UserAuthorization_AuthorizeByFirstStep_Outcoming {
  struct UserAuthorization_AuthorizeByFirstStep_Outcoming filled;
  bool is_filled;
} CData_UserAuthorization_AuthorizeByFirstStep_Outcoming;

typedef struct UserAuthorization_AuthorizeByFirstStep_Precedent {
  bool user__wrong_email_or_nickname_or_password;
} UserAuthorization_AuthorizeByFirstStep_Precedent;

typedef struct CUnifiedReport_UserAuthorization_AuthorizeByFirstStep_Outcoming__UserAuthorization_AuthorizeByFirstStep_Precedent {
  struct CData_UserAuthorization_AuthorizeByFirstStep_Outcoming target;
  struct UserAuthorization_AuthorizeByFirstStep_Precedent precedent;
  bool is_target;
} CUnifiedReport_UserAuthorization_AuthorizeByFirstStep_Outcoming__UserAuthorization_AuthorizeByFirstStep_Precedent;

typedef struct CResult_CUnifiedReport_UserAuthorization_AuthorizeByFirstStep_Outcoming__UserAuthorization_AuthorizeByFirstStep_Precedent {
  struct CUnifiedReport_UserAuthorization_AuthorizeByFirstStep_Outcoming__UserAuthorization_AuthorizeByFirstStep_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_UserAuthorization_AuthorizeByFirstStep_Outcoming__UserAuthorization_AuthorizeByFirstStep_Precedent;

typedef struct CResult_CUnifiedReport_UserAuthorization_AuthorizeByFirstStep_Outcoming__UserAuthorization_AuthorizeByFirstStep_Precedent UserAuthorization_AuthorizeByFirstStep___CResult;

typedef struct UserAuthorization_AuthorizeByLastStep_Incoming {
  long user__id;
  struct CString user_device__id;
  struct CString user_authorization_token__value;
} UserAuthorization_AuthorizeByLastStep_Incoming;

typedef struct UserAccessTokenEncoded {
  struct CVector_c_uchar serialized;
  struct CVector_c_uchar encoded;
} UserAccessTokenEncoded;

typedef struct UserAccessRefreshTokenEncoded {
  struct CVector_c_uchar _0;
} UserAccessRefreshTokenEncoded;

typedef struct UserAuthorization_AuthorizeByLastStep_Outcoming {
  struct UserAccessTokenEncoded user_access_token_encoded;
  struct UserAccessRefreshTokenEncoded user_access_refresh_token_encoded;
} UserAuthorization_AuthorizeByLastStep_Outcoming;

typedef struct CData_UserAuthorization_AuthorizeByLastStep_Outcoming {
  struct UserAuthorization_AuthorizeByLastStep_Outcoming filled;
  bool is_filled;
} CData_UserAuthorization_AuthorizeByLastStep_Outcoming;

typedef struct UserAuthorizationToken_WrongValue {
  bool is_exist;
  short user_authorization_token__wrong_enter_tries_quantity;
} UserAuthorizationToken_WrongValue;

typedef struct UserAuthorization_AuthorizeByLastStep_Precedent {
  bool user_authorization_token__not_found;
  bool user_authorization_token__already_expired;
  struct UserAuthorizationToken_WrongValue user_authorization_token__wrong_value;
  bool user__not_found;
} UserAuthorization_AuthorizeByLastStep_Precedent;

typedef struct CUnifiedReport_UserAuthorization_AuthorizeByLastStep_Outcoming__UserAuthorization_AuthorizeByLastStep_Precedent {
  struct CData_UserAuthorization_AuthorizeByLastStep_Outcoming target;
  struct UserAuthorization_AuthorizeByLastStep_Precedent precedent;
  bool is_target;
} CUnifiedReport_UserAuthorization_AuthorizeByLastStep_Outcoming__UserAuthorization_AuthorizeByLastStep_Precedent;

typedef struct CResult_CUnifiedReport_UserAuthorization_AuthorizeByLastStep_Outcoming__UserAuthorization_AuthorizeByLastStep_Precedent {
  struct CUnifiedReport_UserAuthorization_AuthorizeByLastStep_Outcoming__UserAuthorization_AuthorizeByLastStep_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_UserAuthorization_AuthorizeByLastStep_Outcoming__UserAuthorization_AuthorizeByLastStep_Precedent;

typedef struct CResult_CUnifiedReport_UserAuthorization_AuthorizeByLastStep_Outcoming__UserAuthorization_AuthorizeByLastStep_Precedent UserAuthorization_AuthorizeByLastStep___CResult;

typedef struct UserAuthorization_CheckEmailForExisting_Incoming {
  struct CString user__email;
} UserAuthorization_CheckEmailForExisting_Incoming;

typedef struct UserAuthorization_CheckEmailForExisting_Outcoming {
  bool result;
} UserAuthorization_CheckEmailForExisting_Outcoming;

typedef struct CData_UserAuthorization_CheckEmailForExisting_Outcoming {
  struct UserAuthorization_CheckEmailForExisting_Outcoming filled;
  bool is_filled;
} CData_UserAuthorization_CheckEmailForExisting_Outcoming;

typedef struct CVoid {
  bool _inner;
} CVoid;

typedef struct CUnifiedReport_UserAuthorization_CheckEmailForExisting_Outcoming__CVoid {
  struct CData_UserAuthorization_CheckEmailForExisting_Outcoming target;
  struct CVoid precedent;
  bool is_target;
} CUnifiedReport_UserAuthorization_CheckEmailForExisting_Outcoming__CVoid;

typedef struct CResult_CUnifiedReport_UserAuthorization_CheckEmailForExisting_Outcoming__CVoid {
  struct CUnifiedReport_UserAuthorization_CheckEmailForExisting_Outcoming__CVoid data;
  bool is_data;
} CResult_CUnifiedReport_UserAuthorization_CheckEmailForExisting_Outcoming__CVoid;

typedef struct CResult_CUnifiedReport_UserAuthorization_CheckEmailForExisting_Outcoming__CVoid UserAuthorization_CheckEmailForExisting___CResult;

typedef struct UserAuthorization_CheckNicknameForExisting_Incoming {
  struct CString user__nickname;
} UserAuthorization_CheckNicknameForExisting_Incoming;

typedef struct UserAuthorization_CheckNicknameForExisting_Outcoming {
  bool result;
} UserAuthorization_CheckNicknameForExisting_Outcoming;

typedef struct CData_UserAuthorization_CheckNicknameForExisting_Outcoming {
  struct UserAuthorization_CheckNicknameForExisting_Outcoming filled;
  bool is_filled;
} CData_UserAuthorization_CheckNicknameForExisting_Outcoming;

typedef struct CUnifiedReport_UserAuthorization_CheckNicknameForExisting_Outcoming__CVoid {
  struct CData_UserAuthorization_CheckNicknameForExisting_Outcoming target;
  struct CVoid precedent;
  bool is_target;
} CUnifiedReport_UserAuthorization_CheckNicknameForExisting_Outcoming__CVoid;

typedef struct CResult_CUnifiedReport_UserAuthorization_CheckNicknameForExisting_Outcoming__CVoid {
  struct CUnifiedReport_UserAuthorization_CheckNicknameForExisting_Outcoming__CVoid data;
  bool is_data;
} CResult_CUnifiedReport_UserAuthorization_CheckNicknameForExisting_Outcoming__CVoid;

typedef struct CResult_CUnifiedReport_UserAuthorization_CheckNicknameForExisting_Outcoming__CVoid UserAuthorization_CheckNicknameForExisting___CResult;

typedef struct UserAuthorization_DeauthorizeFromAllDevices_Incoming {
  struct UserAccessTokenEncoded user_access_token_encoded;
} UserAuthorization_DeauthorizeFromAllDevices_Incoming;

typedef struct CData_CVoid {
  struct CVoid filled;
  bool is_filled;
} CData_CVoid;

typedef struct UserAuthorization_DeauthorizeFromAllDevices_Precedent {
  bool user_access_token__already_expired;
  bool user_access_token__in_user_access_token_black_list;
} UserAuthorization_DeauthorizeFromAllDevices_Precedent;

typedef struct CUnifiedReport_CVoid__UserAuthorization_DeauthorizeFromAllDevices_Precedent {
  struct CData_CVoid target;
  struct UserAuthorization_DeauthorizeFromAllDevices_Precedent precedent;
  bool is_target;
} CUnifiedReport_CVoid__UserAuthorization_DeauthorizeFromAllDevices_Precedent;

typedef struct CResult_CUnifiedReport_CVoid__UserAuthorization_DeauthorizeFromAllDevices_Precedent {
  struct CUnifiedReport_CVoid__UserAuthorization_DeauthorizeFromAllDevices_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_CVoid__UserAuthorization_DeauthorizeFromAllDevices_Precedent;

typedef struct CResult_CUnifiedReport_CVoid__UserAuthorization_DeauthorizeFromAllDevices_Precedent UserAuthorization_DeauthorizeFromAllDevices___CResult;

typedef struct UserAuthorization_DeauthorizeFromOneDevice_Incoming {
  struct UserAccessTokenEncoded user_access_token_encoded;
} UserAuthorization_DeauthorizeFromOneDevice_Incoming;

typedef struct UserAuthorization_DeauthorizeFromOneDevice_Precedent {
  bool user_access_token__already_expired;
  bool user_access_token__in_user_access_token_black_list;
} UserAuthorization_DeauthorizeFromOneDevice_Precedent;

typedef struct CUnifiedReport_CVoid__UserAuthorization_DeauthorizeFromOneDevice_Precedent {
  struct CData_CVoid target;
  struct UserAuthorization_DeauthorizeFromOneDevice_Precedent precedent;
  bool is_target;
} CUnifiedReport_CVoid__UserAuthorization_DeauthorizeFromOneDevice_Precedent;

typedef struct CResult_CUnifiedReport_CVoid__UserAuthorization_DeauthorizeFromOneDevice_Precedent {
  struct CUnifiedReport_CVoid__UserAuthorization_DeauthorizeFromOneDevice_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_CVoid__UserAuthorization_DeauthorizeFromOneDevice_Precedent;

typedef struct CResult_CUnifiedReport_CVoid__UserAuthorization_DeauthorizeFromOneDevice_Precedent UserAuthorization_DeauthorizeFromOneDevice___CResult;

typedef struct UserAuthorization_RefreshAccessToken_Incoming {
  struct UserAccessTokenEncoded user_access_token_encoded;
  struct UserAccessRefreshTokenEncoded user_access_refresh_token_encoded;
} UserAuthorization_RefreshAccessToken_Incoming;

typedef struct UserAuthorization_RefreshAccessToken_Outcoming {
  struct UserAccessTokenEncoded user_access_token_encoded;
  struct UserAccessRefreshTokenEncoded user_access_refresh_token_encoded;
} UserAuthorization_RefreshAccessToken_Outcoming;

typedef struct CData_UserAuthorization_RefreshAccessToken_Outcoming {
  struct UserAuthorization_RefreshAccessToken_Outcoming filled;
  bool is_filled;
} CData_UserAuthorization_RefreshAccessToken_Outcoming;

typedef struct UserAuthorization_RefreshAccessToken_Precedent {
  bool user_access_refresh_token__not_found;
  bool user_access_refresh_token__already_expired;
} UserAuthorization_RefreshAccessToken_Precedent;

typedef struct CUnifiedReport_UserAuthorization_RefreshAccessToken_Outcoming__UserAuthorization_RefreshAccessToken_Precedent {
  struct CData_UserAuthorization_RefreshAccessToken_Outcoming target;
  struct UserAuthorization_RefreshAccessToken_Precedent precedent;
  bool is_target;
} CUnifiedReport_UserAuthorization_RefreshAccessToken_Outcoming__UserAuthorization_RefreshAccessToken_Precedent;

typedef struct CResult_CUnifiedReport_UserAuthorization_RefreshAccessToken_Outcoming__UserAuthorization_RefreshAccessToken_Precedent {
  struct CUnifiedReport_UserAuthorization_RefreshAccessToken_Outcoming__UserAuthorization_RefreshAccessToken_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_UserAuthorization_RefreshAccessToken_Outcoming__UserAuthorization_RefreshAccessToken_Precedent;

typedef struct CResult_CUnifiedReport_UserAuthorization_RefreshAccessToken_Outcoming__UserAuthorization_RefreshAccessToken_Precedent UserAuthorization_RefreshAccessToken_CResult;

typedef struct UserAuthorization_RegisterByFirstStep_Incoming {
  struct CString user__email;
  struct CString user_device__id;
} UserAuthorization_RegisterByFirstStep_Incoming;

typedef struct UserAuthorization_RegisterByFirstStep_Outcoming {
  bool verification_message_sent;
  long user_registration_token__can_be_resent_from;
  short user_registration_token__wrong_enter_tries_quantity;
  short user_registration_token__wrong_enter_tries_quantity_limit;
} UserAuthorization_RegisterByFirstStep_Outcoming;

typedef struct CData_UserAuthorization_RegisterByFirstStep_Outcoming {
  struct UserAuthorization_RegisterByFirstStep_Outcoming filled;
  bool is_filled;
} CData_UserAuthorization_RegisterByFirstStep_Outcoming;

typedef struct UserAuthorization_RegisterByFirstStep_Precedent {
  bool user__email_already_exist;
} UserAuthorization_RegisterByFirstStep_Precedent;

typedef struct CUnifiedReport_UserAuthorization_RegisterByFirstStep_Outcoming__UserAuthorization_RegisterByFirstStep_Precedent {
  struct CData_UserAuthorization_RegisterByFirstStep_Outcoming target;
  struct UserAuthorization_RegisterByFirstStep_Precedent precedent;
  bool is_target;
} CUnifiedReport_UserAuthorization_RegisterByFirstStep_Outcoming__UserAuthorization_RegisterByFirstStep_Precedent;

typedef struct CResult_CUnifiedReport_UserAuthorization_RegisterByFirstStep_Outcoming__UserAuthorization_RegisterByFirstStep_Precedent {
  struct CUnifiedReport_UserAuthorization_RegisterByFirstStep_Outcoming__UserAuthorization_RegisterByFirstStep_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_UserAuthorization_RegisterByFirstStep_Outcoming__UserAuthorization_RegisterByFirstStep_Precedent;

typedef struct CResult_CUnifiedReport_UserAuthorization_RegisterByFirstStep_Outcoming__UserAuthorization_RegisterByFirstStep_Precedent UserAuthorization_RegisterByFirstStep___CResult;

typedef struct UserAuthorization_RegisterBySecondStep_Incoming {
  struct CString user__email;
  struct CString user_device__id;
  struct CString user_registration_token__value;
} UserAuthorization_RegisterBySecondStep_Incoming;

typedef struct UserRegistrationToken_WrongValue {
  bool is_exist;
  short user_registration_token__wrong_enter_tries_quantity;
} UserRegistrationToken_WrongValue;

typedef struct UserAuthorization_RegisterBySecondStep_Precedent {
  bool user_registration_token__not_found;
  bool user_registration_token__already_expired;
  bool user_registration_token__already_approved;
  struct UserRegistrationToken_WrongValue user_registration_token__wrong_value;
} UserAuthorization_RegisterBySecondStep_Precedent;

typedef struct CUnifiedReport_CVoid__UserAuthorization_RegisterBySecondStep_Precedent {
  struct CData_CVoid target;
  struct UserAuthorization_RegisterBySecondStep_Precedent precedent;
  bool is_target;
} CUnifiedReport_CVoid__UserAuthorization_RegisterBySecondStep_Precedent;

typedef struct CResult_CUnifiedReport_CVoid__UserAuthorization_RegisterBySecondStep_Precedent {
  struct CUnifiedReport_CVoid__UserAuthorization_RegisterBySecondStep_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_CVoid__UserAuthorization_RegisterBySecondStep_Precedent;

typedef struct CResult_CUnifiedReport_CVoid__UserAuthorization_RegisterBySecondStep_Precedent UserAuthorization_RegisterBySecondStep___CResult;

typedef struct UserAuthorization_RegisterByLastStep_Incoming {
  struct CString user_device__id;
  struct CString user__nickname;
  struct CString user__password;
  struct CString user__email;
  struct CString user_registration_token__value;
} UserAuthorization_RegisterByLastStep_Incoming;

typedef struct UserAuthorization_RegisterByLastStep_Outcoming {
  struct UserAccessTokenEncoded user_access_token_encoded;
  struct UserAccessRefreshTokenEncoded user_access_refresh_token_encoded;
} UserAuthorization_RegisterByLastStep_Outcoming;

typedef struct CData_UserAuthorization_RegisterByLastStep_Outcoming {
  struct UserAuthorization_RegisterByLastStep_Outcoming filled;
  bool is_filled;
} CData_UserAuthorization_RegisterByLastStep_Outcoming;

typedef struct UserAuthorization_RegisterByLastStep_Precedent {
  bool user__nickname_already_exist;
  bool user__email_already_exist;
  bool user_registration_token__not_found;
  bool user_registration_token__already_expired;
  bool user_registration_token__is_not_approved;
  bool user_registration_token__wrong_value;
} UserAuthorization_RegisterByLastStep_Precedent;

typedef struct CUnifiedReport_UserAuthorization_RegisterByLastStep_Outcoming__UserAuthorization_RegisterByLastStep_Precedent {
  struct CData_UserAuthorization_RegisterByLastStep_Outcoming target;
  struct UserAuthorization_RegisterByLastStep_Precedent precedent;
  bool is_target;
} CUnifiedReport_UserAuthorization_RegisterByLastStep_Outcoming__UserAuthorization_RegisterByLastStep_Precedent;

typedef struct CResult_CUnifiedReport_UserAuthorization_RegisterByLastStep_Outcoming__UserAuthorization_RegisterByLastStep_Precedent {
  struct CUnifiedReport_UserAuthorization_RegisterByLastStep_Outcoming__UserAuthorization_RegisterByLastStep_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_UserAuthorization_RegisterByLastStep_Outcoming__UserAuthorization_RegisterByLastStep_Precedent;

typedef struct CResult_CUnifiedReport_UserAuthorization_RegisterByLastStep_Outcoming__UserAuthorization_RegisterByLastStep_Precedent UserAuthorization_RegisterByLastStep___CResult;

typedef struct UserAuthorization_ResetPasswordByFirstStep_Incoming {
  struct CString user__email;
  struct CString user_device__id;
} UserAuthorization_ResetPasswordByFirstStep_Incoming;

typedef struct UserAuthorization_ResetPasswordByFirstStep_Outcoming {
  long user__id;
  bool verification_message_sent;
  long user_reset_password_token__can_be_resent_from;
  short user_reset_password_token__wrong_enter_tries_quantity;
  short user_reset_password_token__wrong_enter_tries_quantity_limit;
} UserAuthorization_ResetPasswordByFirstStep_Outcoming;

typedef struct CData_UserAuthorization_ResetPasswordByFirstStep_Outcoming {
  struct UserAuthorization_ResetPasswordByFirstStep_Outcoming filled;
  bool is_filled;
} CData_UserAuthorization_ResetPasswordByFirstStep_Outcoming;

typedef struct UserAuthorization_ResetPasswordByFirstStep_Precedent {
  bool user__not_found;
} UserAuthorization_ResetPasswordByFirstStep_Precedent;

typedef struct CUnifiedReport_UserAuthorization_ResetPasswordByFirstStep_Outcoming__UserAuthorization_ResetPasswordByFirstStep_Precedent {
  struct CData_UserAuthorization_ResetPasswordByFirstStep_Outcoming target;
  struct UserAuthorization_ResetPasswordByFirstStep_Precedent precedent;
  bool is_target;
} CUnifiedReport_UserAuthorization_ResetPasswordByFirstStep_Outcoming__UserAuthorization_ResetPasswordByFirstStep_Precedent;

typedef struct CResult_CUnifiedReport_UserAuthorization_ResetPasswordByFirstStep_Outcoming__UserAuthorization_ResetPasswordByFirstStep_Precedent {
  struct CUnifiedReport_UserAuthorization_ResetPasswordByFirstStep_Outcoming__UserAuthorization_ResetPasswordByFirstStep_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_UserAuthorization_ResetPasswordByFirstStep_Outcoming__UserAuthorization_ResetPasswordByFirstStep_Precedent;

typedef struct CResult_CUnifiedReport_UserAuthorization_ResetPasswordByFirstStep_Outcoming__UserAuthorization_ResetPasswordByFirstStep_Precedent UserAuthorization_ResetPasswordByFirstStep___CResult;

typedef struct UserAuthorization_ResetPasswordBySecondStep_Incoming {
  long user__id;
  struct CString user_device__id;
  struct CString user_reset_password_token__value;
} UserAuthorization_ResetPasswordBySecondStep_Incoming;

typedef struct UserResetPasswordToken_WrongValue {
  bool is_exist;
  short user_reset_password_token__wrong_enter_tries_quantity;
} UserResetPasswordToken_WrongValue;

typedef struct UserAuthorization_ResetPasswordBySecondStep_Precedent {
  bool user_reset_password_token__not_found;
  bool user_reset_password_token__already_expired;
  bool user_reset_password_token__already_approved;
  struct UserResetPasswordToken_WrongValue user_reset_password_token__wrong_value;
} UserAuthorization_ResetPasswordBySecondStep_Precedent;

typedef struct CUnifiedReport_CVoid__UserAuthorization_ResetPasswordBySecondStep_Precedent {
  struct CData_CVoid target;
  struct UserAuthorization_ResetPasswordBySecondStep_Precedent precedent;
  bool is_target;
} CUnifiedReport_CVoid__UserAuthorization_ResetPasswordBySecondStep_Precedent;

typedef struct CResult_CUnifiedReport_CVoid__UserAuthorization_ResetPasswordBySecondStep_Precedent {
  struct CUnifiedReport_CVoid__UserAuthorization_ResetPasswordBySecondStep_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_CVoid__UserAuthorization_ResetPasswordBySecondStep_Precedent;

typedef struct CResult_CUnifiedReport_CVoid__UserAuthorization_ResetPasswordBySecondStep_Precedent UserAuthorization_ResetPasswordBySecondStep___CResult;

typedef struct UserAuthorization_ResetPasswordByLastStep_Incoming {
  long user__id;
  struct CString user_device__id;
  struct CString user__password;
  struct CString user_reset_password_token__value;
} UserAuthorization_ResetPasswordByLastStep_Incoming;

typedef struct UserAuthorization_ResetPasswordByLastStep_Precedent {
  bool user__not_found;
  bool user_reset_password_token__not_found;
  bool user_reset_password_token__already_expired;
  bool user_reset_password_token__is_not_approved;
  bool user_reset_password_token__wrong_value;
} UserAuthorization_ResetPasswordByLastStep_Precedent;

typedef struct CUnifiedReport_CVoid__UserAuthorization_ResetPasswordByLastStep_Precedent {
  struct CData_CVoid target;
  struct UserAuthorization_ResetPasswordByLastStep_Precedent precedent;
  bool is_target;
} CUnifiedReport_CVoid__UserAuthorization_ResetPasswordByLastStep_Precedent;

typedef struct CResult_CUnifiedReport_CVoid__UserAuthorization_ResetPasswordByLastStep_Precedent {
  struct CUnifiedReport_CVoid__UserAuthorization_ResetPasswordByLastStep_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_CVoid__UserAuthorization_ResetPasswordByLastStep_Precedent;

typedef struct CResult_CUnifiedReport_CVoid__UserAuthorization_ResetPasswordByLastStep_Precedent UserAuthorization_ResetPasswordByLastStep___CResult;

typedef struct UserAuthorization_SendEmailForRegister_Incoming {
  struct CString user__email;
  struct CString user_device__id;
} UserAuthorization_SendEmailForRegister_Incoming;

typedef struct UserAuthorization_SendEmailForRegister_Outcoming {
  long user_registration_token__can_be_resent_from;
} UserAuthorization_SendEmailForRegister_Outcoming;

typedef struct CData_UserAuthorization_SendEmailForRegister_Outcoming {
  struct UserAuthorization_SendEmailForRegister_Outcoming filled;
  bool is_filled;
} CData_UserAuthorization_SendEmailForRegister_Outcoming;

typedef struct UserAuthorization_SendEmailForRegister_Precedent {
  bool user_registration_token__not_found;
  bool user_registration_token__already_expired;
  bool user_registration_token__already_approved;
  bool user_registration_token__time_to_resend_has_not_come;
} UserAuthorization_SendEmailForRegister_Precedent;

typedef struct CUnifiedReport_UserAuthorization_SendEmailForRegister_Outcoming__UserAuthorization_SendEmailForRegister_Precedent {
  struct CData_UserAuthorization_SendEmailForRegister_Outcoming target;
  struct UserAuthorization_SendEmailForRegister_Precedent precedent;
  bool is_target;
} CUnifiedReport_UserAuthorization_SendEmailForRegister_Outcoming__UserAuthorization_SendEmailForRegister_Precedent;

typedef struct CResult_CUnifiedReport_UserAuthorization_SendEmailForRegister_Outcoming__UserAuthorization_SendEmailForRegister_Precedent {
  struct CUnifiedReport_UserAuthorization_SendEmailForRegister_Outcoming__UserAuthorization_SendEmailForRegister_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_UserAuthorization_SendEmailForRegister_Outcoming__UserAuthorization_SendEmailForRegister_Precedent;

typedef struct CResult_CUnifiedReport_UserAuthorization_SendEmailForRegister_Outcoming__UserAuthorization_SendEmailForRegister_Precedent UserAuthorization_SendEmailForRegister___CResult;

typedef struct UserAuthorization_SendEmailForAuthorize_Incoming {
  struct CString user_device__id;
  long user__id;
} UserAuthorization_SendEmailForAuthorize_Incoming;

typedef struct UserAuthorization_SendEmailForAuthorize_Outcoming {
  long user_authorization_token__can_be_resent_from;
} UserAuthorization_SendEmailForAuthorize_Outcoming;

typedef struct CData_UserAuthorization_SendEmailForAuthorize_Outcoming {
  struct UserAuthorization_SendEmailForAuthorize_Outcoming filled;
  bool is_filled;
} CData_UserAuthorization_SendEmailForAuthorize_Outcoming;

typedef struct UserAuthorization_SendEmailForAuthorize_Precedent {
  bool user__not_found;
  bool user_authorization_token__not_found;
  bool user_authorization_token__already_expired;
  bool user_authorization_token__time_to_resend_has_not_come;
} UserAuthorization_SendEmailForAuthorize_Precedent;

typedef struct CUnifiedReport_UserAuthorization_SendEmailForAuthorize_Outcoming__UserAuthorization_SendEmailForAuthorize_Precedent {
  struct CData_UserAuthorization_SendEmailForAuthorize_Outcoming target;
  struct UserAuthorization_SendEmailForAuthorize_Precedent precedent;
  bool is_target;
} CUnifiedReport_UserAuthorization_SendEmailForAuthorize_Outcoming__UserAuthorization_SendEmailForAuthorize_Precedent;

typedef struct CResult_CUnifiedReport_UserAuthorization_SendEmailForAuthorize_Outcoming__UserAuthorization_SendEmailForAuthorize_Precedent {
  struct CUnifiedReport_UserAuthorization_SendEmailForAuthorize_Outcoming__UserAuthorization_SendEmailForAuthorize_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_UserAuthorization_SendEmailForAuthorize_Outcoming__UserAuthorization_SendEmailForAuthorize_Precedent;

typedef struct CResult_CUnifiedReport_UserAuthorization_SendEmailForAuthorize_Outcoming__UserAuthorization_SendEmailForAuthorize_Precedent UserAuthorization_SendEmailForAuthorize___CResult;

typedef struct UserAuthorization_SendEmailForResetPassword_Incoming {
  long user__id;
  struct CString user_device__id;
} UserAuthorization_SendEmailForResetPassword_Incoming;

typedef struct UserAuthorization_SendEmailForResetPassword_Outcoming {
  long user_resep_password_token_can_be_resent_from;
} UserAuthorization_SendEmailForResetPassword_Outcoming;

typedef struct CData_UserAuthorization_SendEmailForResetPassword_Outcoming {
  struct UserAuthorization_SendEmailForResetPassword_Outcoming filled;
  bool is_filled;
} CData_UserAuthorization_SendEmailForResetPassword_Outcoming;

typedef struct UserAuthorization_SendEmailForResetPassword_Precedent {
  bool user__not_found;
  bool user_reset_password_token__not_found;
  bool user_reset_password_token__already_expired;
  bool user_reset_password_token__already_approved;
  bool user_reset_password_token__time_to_resend_has_not_come;
} UserAuthorization_SendEmailForResetPassword_Precedent;

typedef struct CUnifiedReport_UserAuthorization_SendEmailForResetPassword_Outcoming__UserAuthorization_SendEmailForResetPassword_Precedent {
  struct CData_UserAuthorization_SendEmailForResetPassword_Outcoming target;
  struct UserAuthorization_SendEmailForResetPassword_Precedent precedent;
  bool is_target;
} CUnifiedReport_UserAuthorization_SendEmailForResetPassword_Outcoming__UserAuthorization_SendEmailForResetPassword_Precedent;

typedef struct CResult_CUnifiedReport_UserAuthorization_SendEmailForResetPassword_Outcoming__UserAuthorization_SendEmailForResetPassword_Precedent {
  struct CUnifiedReport_UserAuthorization_SendEmailForResetPassword_Outcoming__UserAuthorization_SendEmailForResetPassword_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_UserAuthorization_SendEmailForResetPassword_Outcoming__UserAuthorization_SendEmailForResetPassword_Precedent;

typedef struct CResult_CUnifiedReport_UserAuthorization_SendEmailForResetPassword_Outcoming__UserAuthorization_SendEmailForResetPassword_Precedent UserAuthorization_SendEmailForResetPassword___CResult;

typedef struct COption_CString {
  struct CString data;
  bool is_data;
} COption_CString;

typedef struct Channel_GetManyByNameInSubscriptions_Incoming {
  struct UserAccessTokenEncoded user_access_token_encoded;
  struct CString channel__name;
  struct COption_CString requery___channel__name;
  short limit;
} Channel_GetManyByNameInSubscriptions_Incoming;

typedef struct Channel1 {
  long channel__id;
  struct CString channel__name;
  struct CString channel__linked_name;
  short channel__access_modifier;
  short channel__visability_modifier;
  struct COption_CString channel__cover_image_path;
  struct COption_CString channel__background_image_path;
} Channel1;

typedef struct Common1 {
  struct Channel1 channel;
  bool is_user_subscribed;
} Common1;

typedef struct CVector_Common1 {
  struct Common1 *pointer;
  size_t length;
} CVector_Common1;

typedef struct Channel_GetManyByNameInSubscriptions_Outcoming {
  struct CVector_Common1 common_registry;
} Channel_GetManyByNameInSubscriptions_Outcoming;

typedef struct CData_Channel_GetManyByNameInSubscriptions_Outcoming {
  struct Channel_GetManyByNameInSubscriptions_Outcoming filled;
  bool is_filled;
} CData_Channel_GetManyByNameInSubscriptions_Outcoming;

typedef struct Channel_GetManyByNameInSubscriptions_Precedent {
  bool user_access_token__already_expired;
  bool user_access_token__in_user_access_token_black_list;
} Channel_GetManyByNameInSubscriptions_Precedent;

typedef struct CUnifiedReport_Channel_GetManyByNameInSubscriptions_Outcoming__Channel_GetManyByNameInSubscriptions_Precedent {
  struct CData_Channel_GetManyByNameInSubscriptions_Outcoming target;
  struct Channel_GetManyByNameInSubscriptions_Precedent precedent;
  bool is_target;
} CUnifiedReport_Channel_GetManyByNameInSubscriptions_Outcoming__Channel_GetManyByNameInSubscriptions_Precedent;

typedef struct CResult_CUnifiedReport_Channel_GetManyByNameInSubscriptions_Outcoming__Channel_GetManyByNameInSubscriptions_Precedent {
  struct CUnifiedReport_Channel_GetManyByNameInSubscriptions_Outcoming__Channel_GetManyByNameInSubscriptions_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_Channel_GetManyByNameInSubscriptions_Outcoming__Channel_GetManyByNameInSubscriptions_Precedent;

typedef struct CResult_CUnifiedReport_Channel_GetManyByNameInSubscriptions_Outcoming__Channel_GetManyByNameInSubscriptions_Precedent Channel_GetManyByNameInSubscriptions___CResult;

typedef struct COption_c_long {
  long data;
  bool is_data;
} COption_c_long;

typedef struct Channel_GetManyBySubscription_Incoming {
  struct UserAccessTokenEncoded user_access_token_encoded;
  struct COption_c_long requery___channel__id;
  short limit;
} Channel_GetManyBySubscription_Incoming;

typedef struct Channel_GetManyBySubscription_Outcoming {
  struct CVector_Common1 common_registry;
} Channel_GetManyBySubscription_Outcoming;

typedef struct CData_Channel_GetManyBySubscription_Outcoming {
  struct Channel_GetManyBySubscription_Outcoming filled;
  bool is_filled;
} CData_Channel_GetManyBySubscription_Outcoming;

typedef struct Channel_GetManyBySubscription_Precedent {
  bool user_access_token__already_expired;
  bool user_access_token__in_user_access_token_black_list;
} Channel_GetManyBySubscription_Precedent;

typedef struct CUnifiedReport_Channel_GetManyBySubscription_Outcoming__Channel_GetManyBySubscription_Precedent {
  struct CData_Channel_GetManyBySubscription_Outcoming target;
  struct Channel_GetManyBySubscription_Precedent precedent;
  bool is_target;
} CUnifiedReport_Channel_GetManyBySubscription_Outcoming__Channel_GetManyBySubscription_Precedent;

typedef struct CResult_CUnifiedReport_Channel_GetManyBySubscription_Outcoming__Channel_GetManyBySubscription_Precedent {
  struct CUnifiedReport_Channel_GetManyBySubscription_Outcoming__Channel_GetManyBySubscription_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_Channel_GetManyBySubscription_Outcoming__Channel_GetManyBySubscription_Precedent;

typedef struct CResult_CUnifiedReport_Channel_GetManyBySubscription_Outcoming__Channel_GetManyBySubscription_Precedent Channel_GetManyBySubscription_CResult;

typedef struct Channel_GetManyPublicByName_Incoming {
  struct UserAccessTokenEncoded user_access_token_encoded;
  struct CString channel__name;
  struct COption_CString requery___channel__name;
  short limit;
} Channel_GetManyPublicByName_Incoming;

typedef struct Channel_GetManyPublicByName_Outcoming {
  struct CVector_Common1 common_registry;
} Channel_GetManyPublicByName_Outcoming;

typedef struct CData_Channel_GetManyPublicByName_Outcoming {
  struct Channel_GetManyPublicByName_Outcoming filled;
  bool is_filled;
} CData_Channel_GetManyPublicByName_Outcoming;

typedef struct Channel_GetManyPublicByName_Precedent {
  bool user_access_token__already_expired;
  bool user_access_token__in_user_access_token_black_list;
} Channel_GetManyPublicByName_Precedent;

typedef struct CUnifiedReport_Channel_GetManyPublicByName_Outcoming__Channel_GetManyPublicByName_Precedent {
  struct CData_Channel_GetManyPublicByName_Outcoming target;
  struct Channel_GetManyPublicByName_Precedent precedent;
  bool is_target;
} CUnifiedReport_Channel_GetManyPublicByName_Outcoming__Channel_GetManyPublicByName_Precedent;

typedef struct CResult_CUnifiedReport_Channel_GetManyPublicByName_Outcoming__Channel_GetManyPublicByName_Precedent {
  struct CUnifiedReport_Channel_GetManyPublicByName_Outcoming__Channel_GetManyPublicByName_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_Channel_GetManyPublicByName_Outcoming__Channel_GetManyPublicByName_Precedent;

typedef struct CResult_CUnifiedReport_Channel_GetManyPublicByName_Outcoming__Channel_GetManyPublicByName_Precedent Channel_GetManyPublicByName___CResult;

typedef struct Channel_GetOneById_Incoming {
  struct UserAccessTokenEncoded user_access_token_encoded;
  long channel__id;
} Channel_GetOneById_Incoming;

typedef struct CVector_c_short {
  short *pointer;
  size_t length;
} CVector_c_short;

typedef struct Channel2 {
  long channel__owner;
  struct CString channel__name;
  struct CString channel__linked_name;
  struct COption_CString channel__description;
  short channel__access_modifier;
  short channel__visability_modifier;
  struct CVector_c_short channel__orientation;
  struct COption_CString channel__cover_image_path;
  struct COption_CString channel__background_image_path;
  long channel__subscribers_quantity;
  long channel__marks_quantity;
  long channel__viewing_quantity;
} Channel2;

typedef struct ChannelInnerLink1 {
  long channel_inner_link__to;
} ChannelInnerLink1;

typedef struct CVector_ChannelInnerLink1 {
  struct ChannelInnerLink1 *pointer;
  size_t length;
} CVector_ChannelInnerLink1;

typedef struct ChannelOuterLink1 {
  struct CString channel_outer_link__alias;
  struct CString channel_outer_link__address;
} ChannelOuterLink1;

typedef struct CVector_ChannelOuterLink1 {
  struct ChannelOuterLink1 *pointer;
  size_t length;
} CVector_ChannelOuterLink1;

typedef struct Channel_GetOneById_Outcoming {
  struct Channel2 channel;
  struct CVector_ChannelInnerLink1 channel_inner_link_registry;
  struct CVector_ChannelOuterLink1 channel_outer_link_registry;
} Channel_GetOneById_Outcoming;

typedef struct CData_Channel_GetOneById_Outcoming {
  struct Channel_GetOneById_Outcoming filled;
  bool is_filled;
} CData_Channel_GetOneById_Outcoming;

typedef struct Channel_GetOneById_Precedent {
  bool user_access_token__already_expired;
  bool user_access_token__in_user_access_token_black_list;
  bool channel__not_found;
  bool channel__is_close;
} Channel_GetOneById_Precedent;

typedef struct CUnifiedReport_Channel_GetOneById_Outcoming__Channel_GetOneById_Precedent {
  struct CData_Channel_GetOneById_Outcoming target;
  struct Channel_GetOneById_Precedent precedent;
  bool is_target;
} CUnifiedReport_Channel_GetOneById_Outcoming__Channel_GetOneById_Precedent;

typedef struct CResult_CUnifiedReport_Channel_GetOneById_Outcoming__Channel_GetOneById_Precedent {
  struct CUnifiedReport_Channel_GetOneById_Outcoming__Channel_GetOneById_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_Channel_GetOneById_Outcoming__Channel_GetOneById_Precedent;

typedef struct CResult_CUnifiedReport_Channel_GetOneById_Outcoming__Channel_GetOneById_Precedent Channel_GetOneById___CResult;

typedef struct ChannelSubscription_Create_Incoming {
  struct UserAccessTokenEncoded user_access_token_encoded;
  long channel__id;
} ChannelSubscription_Create_Incoming;

typedef struct ChannelSubscription_Create_Precedent {
  bool user_access_token__already_expired;
  bool user_access_token__in_user_access_token_black_list;
  bool channel__not_found;
  bool channel__is_close;
  bool user__is_channel__owner;
} ChannelSubscription_Create_Precedent;

typedef struct CUnifiedReport_CVoid__ChannelSubscription_Create_Precedent {
  struct CData_CVoid target;
  struct ChannelSubscription_Create_Precedent precedent;
  bool is_target;
} CUnifiedReport_CVoid__ChannelSubscription_Create_Precedent;

typedef struct CResult_CUnifiedReport_CVoid__ChannelSubscription_Create_Precedent {
  struct CUnifiedReport_CVoid__ChannelSubscription_Create_Precedent data;
  bool is_data;
} CResult_CUnifiedReport_CVoid__ChannelSubscription_Create_Precedent;

typedef struct CResult_CUnifiedReport_CVoid__ChannelSubscription_Create_Precedent ChannelSubscription_Create___CResult;

struct CResult_CVector_c_uchar *user_authorization__authorize_by_first_step__serialize_allocate(struct UserAuthorization_AuthorizeByFirstStep_Incoming *incoming);

void user_authorization__authorize_by_first_step__serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

UserAuthorization_AuthorizeByFirstStep___CResult *user_authorization__authorize_by_first_step__deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void user_authorization__authorize_by_first_step__deserialize_deallocate(UserAuthorization_AuthorizeByFirstStep___CResult *c_result);

struct CResult_CVector_c_uchar *user_authorization__authorize_by_last_step__serialize_allocate(struct UserAuthorization_AuthorizeByLastStep_Incoming *incoming);

void user_authorization__authorize_by_last_step__serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

UserAuthorization_AuthorizeByLastStep___CResult *user_authorization__authorize_by_last_step__deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void user_authorization__authorize_by_last_step__deserialize_deallocate(UserAuthorization_AuthorizeByLastStep___CResult *c_result);

struct CResult_CVector_c_uchar *user_authorization____check_email_for_existing____serialize_allocate(struct UserAuthorization_CheckEmailForExisting_Incoming *incoming);

void user_authorization____check_email_for_existing____serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

UserAuthorization_CheckEmailForExisting___CResult *user_authorization____check_email_for_existing____deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void user_authorization____check_email_for_existing____deserialize_deallocate(UserAuthorization_CheckEmailForExisting___CResult *c_result);

struct CResult_CVector_c_uchar *user_authorization____check_nickname_for_existing____serialize_allocate(struct UserAuthorization_CheckNicknameForExisting_Incoming *incoming);

void user_authorization____check_nickname_for_existing____serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

UserAuthorization_CheckNicknameForExisting___CResult *user_authorization____check_nickname_for_existing____deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void user_authorization____check_nickname_for_existing____deserialize_deallocate(UserAuthorization_CheckNicknameForExisting___CResult *c_result);

struct CResult_CVector_c_uchar *user_authorization____deauthorize_from_all_devices____serialize_allocate(struct UserAuthorization_DeauthorizeFromAllDevices_Incoming *incoming);

void user_authorization____deauthorize_from_all_devices____serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

UserAuthorization_DeauthorizeFromAllDevices___CResult *user_authorization____deauthorize_from_all_devices____deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void user_authorization____deauthorize_from_all_devices____deserialize_deallocate(UserAuthorization_DeauthorizeFromAllDevices___CResult *c_result);

struct CResult_CVector_c_uchar *user_authorization____deauthorize_from_one_device____serialize_allocate(struct UserAuthorization_DeauthorizeFromOneDevice_Incoming *incoming);

void user_authorization____deauthorize_from_one_device____serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

UserAuthorization_DeauthorizeFromOneDevice___CResult *user_authorization____deauthorize_from_one_device_deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void user_authorization____deauthorize_from_one_device_deserialize_deallocate(UserAuthorization_DeauthorizeFromOneDevice___CResult *c_result);

struct CResult_CVector_c_uchar *user_authorization____refresh_access_token____serialize_allocate(struct UserAuthorization_RefreshAccessToken_Incoming *incoming);

void user_authorization____refresh_access_token____serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

UserAuthorization_RefreshAccessToken_CResult *user_authorization____refresh_access_token____deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void user_authorization____refresh_access_token____deserialize_deallocate(UserAuthorization_RefreshAccessToken_CResult *c_result);

struct CResult_CVector_c_uchar *user_authorization____register_by_first_step__serialize_allocate(struct UserAuthorization_RegisterByFirstStep_Incoming *incoming);

void user_authorization____register_by_first_step__serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

UserAuthorization_RegisterByFirstStep___CResult *user_authorization____register_by_first_step__deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void user_authorization____register_by_first_step__deserialize_deallocate(UserAuthorization_RegisterByFirstStep___CResult *c_result);

struct CResult_CVector_c_uchar *user_authorization____register_by_second_step__serialize_allocate(struct UserAuthorization_RegisterBySecondStep_Incoming *incoming);

void user_authorization____register_by_second_step__serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

UserAuthorization_RegisterBySecondStep___CResult *user_authorization____register_by_second_step__deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void user_authorization____register_by_second_step__deserialize_deallocate(UserAuthorization_RegisterBySecondStep___CResult *c_result);

struct CResult_CVector_c_uchar *user_authorization____register_by_last_step__serialize_allocate(struct UserAuthorization_RegisterByLastStep_Incoming *incoming);

void user_authorization____register_by_last_step__serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

UserAuthorization_RegisterByLastStep___CResult *user_authorization____register_by_last_step__deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void user_authorization____register_by_last_step__deserialize_deallocate(UserAuthorization_RegisterByLastStep___CResult *c_result);

struct CResult_CVector_c_uchar *user_authorization____reset_password_by_first_step__serialize_allocate(struct UserAuthorization_ResetPasswordByFirstStep_Incoming *incoming);

void user_authorization____reset_password_by_first_step__serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

UserAuthorization_ResetPasswordByFirstStep___CResult *user_authorization____reset_password_by_first_step__deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void user_authorization____reset_password_by_first_step__deserialize_deallocate(UserAuthorization_ResetPasswordByFirstStep___CResult *c_result);

struct CResult_CVector_c_uchar *user_authorization____reset_password_by_second_step__serialize_allocate(struct UserAuthorization_ResetPasswordBySecondStep_Incoming *incoming);

void user_authorization____reset_password_by_second_step__serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

UserAuthorization_ResetPasswordBySecondStep___CResult *user_authorization____reset_password_by_second_step__deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void user_authorization____reset_password_by_second_step__deserialize_deallocate(UserAuthorization_ResetPasswordBySecondStep___CResult *c_result);

struct CResult_CVector_c_uchar *user_authorization____reset_password_by_last_step__serialize_allocate(struct UserAuthorization_ResetPasswordByLastStep_Incoming *incoming);

void user_authorization____reset_password_by_last_step__serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

UserAuthorization_ResetPasswordByLastStep___CResult *user_authorization____reset_password_by_last_step__deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void user_authorization____reset_password_by_last_step__deserialize_deallocate(UserAuthorization_ResetPasswordByLastStep___CResult *c_result);

struct CResult_CVector_c_uchar *user_authorization____send_email_for_register____serialize_allocate(struct UserAuthorization_SendEmailForRegister_Incoming *incoming);

void user_authorization____send_email_for_register____serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

UserAuthorization_SendEmailForRegister___CResult *user_authorization____send_email_for_register____deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void user_authorization____send_email_for_register____deserialize_deallocate(UserAuthorization_SendEmailForRegister___CResult *c_result);

struct CResult_CVector_c_uchar *user_authorization____send_email_for_authorize____serialize_allocate(struct UserAuthorization_SendEmailForAuthorize_Incoming *incoming);

void user_authorization____send_email_for_authorize____serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

UserAuthorization_SendEmailForAuthorize___CResult *user_authorization____send_email_for_authorize_deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void user_authorization____send_email_for_authorize_deserialize_deallocate(UserAuthorization_SendEmailForAuthorize___CResult *c_result);

struct CResult_CVector_c_uchar *user_authorization____send_email_for_reset_password____serialize_allocate(struct UserAuthorization_SendEmailForResetPassword_Incoming *incoming);

void user_authorization____send_email_for_reset_password____serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

UserAuthorization_SendEmailForResetPassword___CResult *user_authorization____send_email_for_reset_password____deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void user_authorization____send_email_for_reset_password____deserialize_deallocate(UserAuthorization_SendEmailForResetPassword___CResult *c_result);

struct CResult_CVector_c_uchar *channel___base____get_many_by_name_in_subscriptions____serialize_allocate(struct Channel_GetManyByNameInSubscriptions_Incoming *incoming);

void channel___base____get_many_by_name_in_subscriptions____serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

Channel_GetManyByNameInSubscriptions___CResult *channel___base____get_many_by_name_in_subscriptions____deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void channel___base____get_many_by_name_in_subscriptions____deserialize_deallocate(Channel_GetManyByNameInSubscriptions___CResult *c_result);

struct CResult_CVector_c_uchar *channel___base____get_many_by_subscription____serialize_allocate(struct Channel_GetManyBySubscription_Incoming *incoming);

void channel___base____get_many_by_subscription____serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

Channel_GetManyBySubscription_CResult *channel___base____get_many_by_subscription____deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void channel___base____get_many_by_subscription____deserialize_deallocate(Channel_GetManyBySubscription_CResult *c_result);

struct CResult_CVector_c_uchar *channel___base____get_many_public_by_name____serialize_allocate(struct Channel_GetManyPublicByName_Incoming *incoming);

void channel___base____get_many_public_by_name____serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

Channel_GetManyPublicByName___CResult *channel___base____get_many_public_by_name_deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void channel___base____get_many_public_by_name_deserialize_deallocate(Channel_GetManyPublicByName___CResult *c_result);

struct CResult_CVector_c_uchar *channel___base____get_one_by_id____serialize_allocate(struct Channel_GetOneById_Incoming *incoming);

void channel___base____get_one_by_id____serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

Channel_GetOneById___CResult *channel___base____get_one_by_id____deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void channel___base____get_one_by_id____deserialize_deallocate(Channel_GetOneById___CResult *c_result);

struct CResult_CVector_c_uchar *channel_subscription___base____create____serialize_allocate(struct ChannelSubscription_Create_Incoming *incoming);

void channel_subscription___base____create____serialize_deallocate(struct CResult_CVector_c_uchar *c_result);

ChannelSubscription_Create___CResult *channel_subscription___base____create_deserialize_allocate(struct CVector_c_uchar *c_vector_of_bytes);

void channel_subscription___base____create_deserialize_deallocate(ChannelSubscription_Create___CResult *c_result);
