[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-Aclippy::collapsible_else_if",
    "-Aclippy::collapsible_match",
    "-Aclippy::explicit_into_iter_loop",
    "-Aclippy::match_wildcard_for_single_variants",
    "-Aclippy::module_inception",
    "-Aclippy::needless_continue",
    "-Aclippy::needless_lifetimes",
    "-Aclippy::needless_return",
    "-Aclippy::new_without_default",
    "-Aclippy::redundant_pattern_matching",
    "-Aclippy::single_match_else",
    "-Aclippy::string_add",
    "-Aclippy::too_many_arguments",
    "-Aclippy::trait_duplication_in_bounds",
    "-Aclippy::unnecessary_cast",
    "-Aclippy::unused_unit",
    "-Dclippy::await_holding_lock",
    "-Dclippy::char_lit_as_u8",
    "-Dclippy::checked_conversions",
    "-Dclippy::dbg_macro",
    "-Dclippy::debug_assert_with_mut_call",
    "-Dclippy::doc_markdown",
    "-Dclippy::empty_enum",
    "-Dclippy::exit",
    "-Dclippy::expl_impl_clone_on_copy",
    "-Dclippy::explicit_deref_methods",
    "-Dclippy::fallible_impl_from",
    "-Dclippy::float_cmp_const",
    "-Dclippy::from_iter_instead_of_collect",
    "-Dclippy::if_let_mutex",
    "-Dclippy::implicit_clone",
    "-Dclippy::imprecise_flops",
    "-Dclippy::inefficient_to_string",
    "-Dclippy::invalid_upcast_comparisons",
    "-Dclippy::large_digit_groups",
    "-Dclippy::large_stack_arrays",
    "-Dclippy::large_types_passed_by_value",
    "-Dclippy::let_unit_value",
    "-Dclippy::linkedlist",
    "-Dclippy::lossy_float_literal",
    "-Dclippy::macro_use_imports",
    "-Dclippy::manual_ok_or",
    "-Dclippy::map_err_ignore",
    "-Dclippy::match_on_vec_items",
    "-Dclippy::match_same_arms",
    "-Dclippy::match_wild_err_arm",
    "-Dclippy::mem_forget",
    "-Dclippy::missing_enforced_import_renames",
    "-Dclippy::mut_mut",
    "-Dclippy::mutex_integer",
    "-Dclippy::needless_borrow",
    "-Dclippy::needless_for_each",
    "-Dclippy::option_option",
    "-Dclippy::path_buf_push_overwrite",
    "-Dclippy::ptr_as_ptr",
    "-Dclippy::rc_mutex",
    "-Dclippy::ref_option_ref",
    "-Dclippy::rest_pat_in_fully_bound_structs",
    "-Dclippy::same_functions_in_if_condition",
    "-Dclippy::semicolon_if_nothing_returned",
    "-Dclippy::string_add_assign",
    "-Dclippy::string_lit_as_bytes",
    "-Dclippy::string_to_string",
    "-Dclippy::todo",
    "-Dclippy::unimplemented",
    "-Dclippy::unnested_or_patterns",
    "-Dclippy::unused_self",
    "-Dclippy::useless_transmute",
    "-Dclippy::verbose_file_reads",
    "-Dclippy::zero_sized_map_values"
]

# TODO TODO TODO Дописать все известные.