[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-Aclippy::collapsible_match",
    "-Aclippy::needless_lifetimes",
    "-Aclippy::needless_return",
    "-Aclippy::redundant_pattern_matching",
    "-Aclippy::unused_unit"
]