FROM rust:1.65.0

RUN \
mkdir -p /_tento && \
rustup default stable && \
rustup component add \
    clippy \
    rust-src && \
rustup target add \
    aarch64-apple-ios \
    x86_64-apple-ios && \
apt-get update && \
apt-get install -y \
    cron \
    pkg-config \
    libssl-dev && \
cargo install diesel_cli --no-default-features --features postgres

# TODO TODO TODO для чего pkg-config, libssl-dev? МОжно ли без них?