FROM rust:1.56.1

RUN \
mkdir -p /usr/local/memis && \
# For VSCode extensions {
# For "matklad.rust-analyzer and "rust-lang.rust" extensions {
rustup component add \
    rust-src && \
# For "matklad.rust-analyzer and "rust-lang.rust" extensions }
# For "rust-lang.rust" extension {
rustup component add \
    rust-analysis \
    rls && \
# For "rust-lang.rust" extension }
# For VSCode extensions }
apt-get update && \
apt-get install -y \
    pkg-config \
    libssl-dev && \
                                                                        # TODO TODO TODO для чего pkg-config, libssl-dev? МОжно ли без них?
cargo install diesel_cli --no-default-features --features postgres
    