[application_server]

[application_server.tcp]

[application_server.tcp.socket_address]
value = "0.0.0.0:80"

[application_server.tcp.nodelay]
value = false

[application_server.tcp.sleep_on_accept_errors]
value = false

[application_server.tcp.keepalive_seconds]
value = 60
is_exist = false

[application_server.http]

[application_server.http.adaptive_window]
value = false

[application_server.http.connection_window_size]
value = 1048576    #1MB

[application_server.http.stream_window_size]
value = 1048576    #1MB

[application_server.http.maximum_frame_size]
value = 16384  #16KB

[application_server.http.maximum_sending_buffer_size]
value = 409600    #400KB

[application_server.http.keepalive]
is_exist = false

[application_server.http.keepalive.interval_seconds]
value = 5

[application_server.http.keepalive.timeout_seconds]
value = 20

[application_server.http.tls]
is_exist = false

[application_server.http.tls.certificate_crt_path]
value = ""

[application_server.http.tls.certificate_key_path]
value = ""

[resource]

[resource.postgresql]

[resource.postgresql.database_1_url]
value = "postgres://root:password@database_1_postgresql/tento"

[resource.postgresql.database_2_url]
value = "postgres://root:password@database_2_postgresql/tento"

[resource.redis]

[resource.redis.database_1_url]
value = "redis://redis"

[resource.email_server]

[resource.email_server.socket_address]
value = "mailhog:1025"

[encryption]

[encryption.private_key]

[encryption.private_key.application_user_access_token]
value = "JJJDffsFi3sc8Mz2udB0qRbz8zH12asu4S1ksSsZ6e2v8cs5fFm6dcfLksWeYY2i"

[encryption.private_key.application_user_access_refresh_token]
value = "SSSDffsFi3sc8Mz2idB0qRbz8zH12asu4S1wsSsZ6e2v8cs5fFm6dcfLksWeYY0i"