version: '3.8'

services: 
    rust_language:
        container_name: memis_rust_language
        build:
            context: ./service/rust_language/
            dockerfile: dockerfile
        environment: 
            USER: ${USER}
        volumes:
            - ./../../../../:/_memis
        ports:
            - 80:80
        working_dir: /_memis
        restart: always
        tty: true
        init: true

networks:
    default:
        name: resource
        driver: bridge