version: '3.8'

services: 
    rust:
        container_name: memis_rust
        build:
            context: ./service/rust/
            dockerfile: dockerfile
        environment: 
            USER: ${USER}
        volumes:
            - ./../../../:/usr/local/memis/
        ports:
            - 8080:80
        working_dir: /usr/local/memis/application/
        restart: always
        tty: true
        init: true